<a href="https://colab.research.google.com/github/riyagupta20csu269/RL/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# R matrix
R=np.matrix([[-1,-1,-1,-1,0,-1],
             [-1,-1,-1,0,-1,100],
             [-1,-1,-1,0,-1,-1],
             [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
             [-1,0,-1,-1,0,100]])

In [4]:
Q=np.matrix(np.zeros([6,6]))

In [5]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [6]:
gamma=0.8
initial_state=1

In [10]:
def available_actions(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act

In [12]:
available_act=available_actions(initial_state)

In [13]:
available_act

array([3, 5])

In [15]:
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [16]:
#sample next action to be performed 
action=sample_next_action(available_act)

In [17]:
action

3

In [18]:
def update(current_state,action,gamma):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
  if max_index.shape[0]>1:
     max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index=int(max_index)
  max_value=Q[action,max_index]

  Q[current_state,action]=R[current_state,action]+gamma*max_value

update(initial_state,action,gamma)

In [19]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [20]:
for i in range(10000):
  current_state=np.random.randint(0,int(Q.shape[0]))
  available_act=available_actions(current_state)
  action=sample_next_action(available_act)
  update(current_state,action,gamma)

In [21]:
Q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [  0., 400., 256.,   0.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [23]:
#normalize
print("trained Q matrix")
print(Q/np.max(Q)*100)

trained Q matrix
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]
